export const RECIPE_REQUEST = 'RECIPE_REQUEST';
export const RECIPE_SUCCESS = 'RECIPE_SUCCESS';
export const RECIPE_ERROR = 'RECIPE_ERROR';

export const GET_CURRENT_RECIPE_REQUEST = 'GET_CURRENT_RECIPE_REQUEST';
export const GET_CURRENT_RECIPE_SUCCESS = 'GET_CURRENT_RECIPE_SUCCESS';
export const GET_CURRENT_RECIPE_ERROR = 'GET_CURRENT_RECIPE_ERROR';

export const CREATE_RECIPE_REQUEST = 'CREATE_RECIPE_REQUEST';
export const CREATE_RECIPE_SUCCESS = 'CREATE_RECIPE_SUCCESS';
export const CREATE_RECIPE_ERROR = 'CREATE_RECIPE_ERROR';

export const DELETE_RECIPE_REQUEST = 'DELETE_RECIPE_REQUEST';
export const DELETE_RECIPE_SUCCESS = 'DELETE_RECIPE_SUCCESS';
export const DELETE_RECIPE_ERROR = 'DELETE_RECIPE_ERROR';

export const EDIT_RECIPE_REQUEST = 'EDIT_RECIPE_REQUEST';
export const EDIT_RECIPE_SUCCESS = 'EDIT_RECIPE_SUCCESS';
export const EDIT_RECIPE_ERROR = 'EDIT_RECIPE_ERROR';

export const CLEAR_SINGLE_RECIPE = 'CLEAR_SINGLE_RECIPE';