export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

export const REGISTR_REQUEST = 'REGISTR_REQUEST';
export const REGISTR_SUCCESS = 'REGISTR_SUCCESS';
export const REGISTR_ERROR = 'REGISTR_ERROR';
